mlcet_analytics:
  target: dev
  outputs:
    dev:
      dataset: mlcet_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /root/.secrets/gcp-zoomcamp-credentials.json
      location: europe-west6
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 1
      type: bigquery
    prod:
      dataset: mlcet_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /root/.secrets/gcp-zoomcamp-credentials.json
      location: europe-west6
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 1
      type: bigquery
